# Generated by Django 2.2.3 on 2021-02-11 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_auto_20210211_0155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0002_secretarionoticia_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('mensaje', models.CharField(max_length=1999)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias')),
                ('created', models.DateField(auto_now_add=True)),
                ('materia', models.ManyToManyField(to='usuarios.Materia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secretario Noticia',
                'verbose_name_plural': 'Secretario Noticias',
            },
        ),
    ]
