# Generated by Django 2.2.3 on 2021-02-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20210214_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretarionoticia',
            name='profesores',
            field=models.BooleanField(default=None),
        ),
    ]
