# Generated by Django 2.2.3 on 2021-02-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_auto_20210214_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretarionoticia',
            name='estudiante',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='secretarionoticia',
            name='preceptor',
            field=models.BooleanField(default=None),
        ),
    ]
