# Generated by Django 2.2.3 on 2021-02-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_remove_secretarionoticia_preceptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretarionoticia',
            name='preceptor',
            field=models.BooleanField(default=None),
        ),
    ]
