# Generated by Django 2.2.3 on 2021-02-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0013_secretarionoticia_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretarionoticia',
            name='estudiante',
            field=models.BooleanField(default=None),
        ),
    ]
