# Generated by Django 2.2.3 on 2021-02-15 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_auto_20210211_0155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0014_secretarionoticia_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesornoticia',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='secretarionoticia',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='PreceptorNoticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=1999)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/preceptor')),
                ('created', models.DateField(auto_now_add=True)),
                ('curso', models.ManyToManyField(to='usuarios.Cursoos')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preceptor Noticia',
                'verbose_name_plural': 'Preceptores Noticias',
            },
        ),
    ]
