# Generated by Django 2.2.3 on 2021-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0016_auto_20210227_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preceptornoticia',
            name='curso',
            field=models.ManyToManyField(blank=True, null=True, to='usuarios.Cursoos'),
        ),
        migrations.AlterField(
            model_name='preceptornoticia',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profesornoticia',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
