# Generated by Django 2.2.3 on 2021-03-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0017_auto_20210228_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesornoticia',
            name='materia',
            field=models.ManyToManyField(blank=True, null=True, to='usuarios.Materia'),
        ),
    ]
