# Generated by Django 2.2.3 on 2021-03-03 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0018_auto_20210301_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesornoticia',
            name='mensaje',
            field=models.TextField(max_length=1999),
        ),
        migrations.CreateModel(
            name='ProfesorNoticiaComentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=400)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
