# Generated by Django 2.2.3 on 2021-03-03 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0019_auto_20210302_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesornoticiacomentarios',
            options={'verbose_name': 'Profesor Comenario', 'verbose_name_plural': 'Profesores Comentarios'},
        ),
        migrations.AddField(
            model_name='profesornoticiacomentarios',
            name='noticia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noticias.ProfesorNoticia'),
        ),
    ]
