# Generated by Django 2.2.3 on 2021-01-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volder_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='curso_y_division',
        ),
        migrations.AddField(
            model_name='cursos',
            name='curso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='division',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
