# Generated by Django 2.2.3 on 2021-01-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volder_app', '0003_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='division',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='nombre',
        ),
    ]
