# Generated by Django 2.2.3 on 2021-01-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_estudiante_curso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Cursoos',
        ),
    ]
