# Generated by Django 2.2.3 on 2021-01-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_estudiante_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
