# Generated by Django 2.2.3 on 2021-01-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20210119_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha_de_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_de_entrega', models.DateTimeField()),
                ('consigna', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('fuentes', models.CharField(max_length=50)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Materia')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Profesor')),
                ('tipo_de_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.TipoDeTarea')),
            ],
        ),
    ]
