# Generated by Django 2.2.3 on 2021-01-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_trabajo_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Profesor'),
        ),
    ]
