# Generated by Django 2.2.3 on 2021-01-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_materia_trabajos_entreagado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='trabajos_entreagado',
            new_name='trabajos_entregados',
        ),
    ]
