# Generated by Django 2.2.3 on 2021-01-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_preceptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='email',
        ),
    ]
