# Generated by Django 2.2.3 on 2021-02-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_secretario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='email',
        ),
        migrations.AddField(
            model_name='preceptor',
            name='dni',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
