# Generated by Django 2.2.3 on 2021-02-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_auto_20210210_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preceptor',
            name='cursos',
            field=models.ManyToManyField(blank=True, null=True, to='usuarios.Cursoos'),
        ),
    ]
