# Generated by Django 2.2.3 on 2021-02-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_auto_20210215_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['apellido']},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='preceptor',
            options={'ordering': ['apellido']},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['apellido']},
        ),
    ]
