# Generated by Django 2.2.3 on 2021-04-18 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_auto_20210223_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursoos',
            options={'ordering': ['curso']},
        ),
        migrations.AlterModelOptions(
            name='trabajo',
            options={'ordering': ['fecha_de_subida']},
        ),
        migrations.CreateModel(
            name='respuestaTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=400, null=True)),
                ('archivo', models.FileField(upload_to='respuestas-trabajo/%Y/%m/%d/')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Estudiante')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Trabajo')),
            ],
        ),
    ]
