# Generated by Django 2.2.3 on 2021-04-19 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_auto_20210419_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajo',
            options={'ordering': ['-fecha_de_subida']},
        ),
        migrations.AlterField(
            model_name='notatrabajo',
            name='nota',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notatrabajo',
            name='respuestaTrabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.RespuestaTrabajo'),
        ),
    ]
