# Generated by Django 2.2.3 on 2021-02-23 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona1', to=settings.AUTH_USER_MODEL)),
                ('persona2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=1000)),
                ('id_conversacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mensajes.Grupo_chat')),
            ],
        ),
    ]
