# Generated by Django 2.2.3 on 2021-02-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_mensajes_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='id_conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensajes.Grupo_chat'),
        ),
    ]
